server:
  port: 8761

spring:
  application:
    name: discoveryService
  cloud:
    config:
      uri: http://localhost:8888
      name: ecommerce

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false